# Generated by Django 5.1.6 on 2025-03-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_work_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
    ]
