# Generated by Django 5.1.6 on 2025-03-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_work_name'),
        ('specialists', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='services',
        ),
        migrations.AddField(
            model_name='specialist',
            name='works',
            field=models.ManyToManyField(related_name='works', to='services.work'),
        ),
    ]
