# Generated by Django 5.1.6 on 2025-03-12 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_category_options_alter_service_options'),
        ('specialists', '0004_remove_specialist_works_specialist_works'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='works',
        ),
        migrations.AddField(
            model_name='specialist',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='services.work'),
        ),
    ]
